# Generated by Django 5.1.6 on 2025-04-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Geoserver_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_name",
                    models.CharField(max_length=100, null=True, unique=True),
                ),
                ("geo_publish", models.BooleanField(default=False)),
                ("raster_visual_id", models.IntegerField()),
            ],
        ),
    ]
