services:
  backend:
    build:
      context: ./backend/
      dockerfile: docker/dockerfile.backend
    image: backend:latest
    ports:
      - "9000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/home/app
    command: /bin/sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: always
    depends_on:
      - db
      - geoserver

    
  db:
    image: postgres:15-alpine
    ports:
      - "5440:5432"
    restart: always
    expose:
      - "5440"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  geoserver:
    image: kartoza/geoserver:latest
    ports:
      - "9090:8080"
    restart: always
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
      - ./backend/media:/opt/geoserver/media
    env_file:
      - .env

volumes:
  postgres_data:
  geoserver_data: