# Generated by Django 5.1.7 on 2025-03-27 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basic_state',
            fields=[
                ('state_code', models.IntegerField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Population_2011',
            fields=[
                ('subdistrict_code', models.IntegerField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=40)),
                ('population_1951', models.BigIntegerField()),
                ('population_1961', models.BigIntegerField()),
                ('population_1971', models.BigIntegerField()),
                ('population_1981', models.BigIntegerField()),
                ('population_1991', models.BigIntegerField()),
                ('population_2001', models.BigIntegerField()),
                ('population_2011', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Basic_district',
            fields=[
                ('district_code', models.IntegerField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=40)),
                ('state_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Basic.basic_state')),
            ],
        ),
        migrations.CreateModel(
            name='Basic_subdistrict',
            fields=[
                ('subdistrict_code', models.IntegerField(primary_key=True, serialize=False)),
                ('subdistrict_name', models.CharField(max_length=40)),
                ('district_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Basic.basic_district')),
            ],
        ),
        migrations.CreateModel(
            name='Basic_village',
            fields=[
                ('village_code', models.IntegerField(primary_key=True, serialize=False)),
                ('village_name', models.CharField(max_length=100)),
                ('population_2011', models.IntegerField()),
                ('subdistrict_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Basic.basic_subdistrict')),
            ],
        ),
    ]
