# Generated by Django 5.1.7 on 2025-03-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RasterVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('file_location', models.FileField(upload_to='raster/')),
            ],
        ),
    ]
